// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8DdafzQLg89kmcHQ-J5A3q1Ak6fQO3o',
    appId: '1:26109806229:web:93416d6e8f7bbf3ca73d9c',
    messagingSenderId: '26109806229',
    projectId: 'tt-ansiedad-sistema',
    authDomain: 'tt-ansiedad-sistema.firebaseapp.com',
    storageBucket: 'tt-ansiedad-sistema.firebasestorage.app',
    measurementId: 'G-5C6N8JX6YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk73os6cJnnotcmEOukDvhuCJxwmQZwaU',
    appId: '1:26109806229:android:90c8819ae12fb171a73d9c',
    messagingSenderId: '26109806229',
    projectId: 'tt-ansiedad-sistema',
    storageBucket: 'tt-ansiedad-sistema.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSQriKHLwhSzodKClna7-0VWvDy9qGz-w',
    appId: '1:26109806229:ios:8433816d25d4e1cea73d9c',
    messagingSenderId: '26109806229',
    projectId: 'tt-ansiedad-sistema',
    storageBucket: 'tt-ansiedad-sistema.firebasestorage.app',
    iosBundleId: 'com.example.appAnsiedad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSQriKHLwhSzodKClna7-0VWvDy9qGz-w',
    appId: '1:26109806229:ios:8433816d25d4e1cea73d9c',
    messagingSenderId: '26109806229',
    projectId: 'tt-ansiedad-sistema',
    storageBucket: 'tt-ansiedad-sistema.firebasestorage.app',
    iosBundleId: 'com.example.appAnsiedad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT8DdafzQLg89kmcHQ-J5A3q1Ak6fQO3o',
    appId: '1:26109806229:web:44483c71de04a368a73d9c',
    messagingSenderId: '26109806229',
    projectId: 'tt-ansiedad-sistema',
    authDomain: 'tt-ansiedad-sistema.firebaseapp.com',
    storageBucket: 'tt-ansiedad-sistema.firebasestorage.app',
    measurementId: 'G-C02JFG1B2Y',
  );
}
